### ISSUE TITLE
A document without a table of contents or without a chapter crashes to build

### ISSUE THREAD

**Issue by frol** [brechtm/rinohtype#11]
The minimal working document is:

```rst
.. contents:: Table of Contents

Structural Elements
===================
```

If I remove any line from here I will get the following traceback:

```python
Traceback (most recent call last):
  File "/tmp/env/bin/rinoh", line 5, in <module>
    main()
  File "/tmp/env/lib/python3.5/site-packages/rinoh/tool.py", line 43, in main
    document.render(input_base)
  File "/tmp/env/lib/python3.5/site-packages/rinoh/document.py", line 313, in render
    section_num_pages = self.render_pages()
  File "/tmp/env/lib/python3.5/site-packages/rinoh/document.py", line 333, in render_pages
    section_page_count = section.render(sum(section_page_counts))
  File "/tmp/env/lib/python3.5/site-packages/rinoh/document.py", line 206, in render
    part_page_count = part.render(doc_page_count + section_page_count)
  File "/tmp/env/lib/python3.5/site-packages/rinoh/document.py", line 152, in render
    chains_requiring_new_page = set(chain for chain in page.render())
  File "/tmp/env/lib/python3.5/site-packages/rinoh/document.py", line 152, in <genexpr>
    chains_requiring_new_page = set(chain for chain in page.render())
  File "/tmp/env/lib/python3.5/site-packages/rinoh/document.py", line 109, in render
    for chain in super().render(rerender=index > 0):
  File "/tmp/env/lib/python3.5/site-packages/rinoh/layout.py", line 221, in render
    for chain in child.render(rerender):
  File "/tmp/env/lib/python3.5/site-packages/rinoh/layout.py", line 225, in render
    height, last_descender = flowable.flow(self, last_descender)
  File "/tmp/env/lib/python3.5/site-packages/rinoh/flowable.py", line 123, in flow
    state=state, **kwargs)
  File "/tmp/env/lib/python3.5/site-packages/rinoh/paragraph.py", line 293, in render
    word = state.next_word()
  File "/tmp/env/lib/python3.5/site-packages/rinoh/paragraph.py", line 238, in next_word
    word = next(self._words)
  File "/tmp/env/lib/python3.5/site-packages/rinoh/paragraph.py", line 200, in spans_to_words
    for chars in span.split(container):
  File "/tmp/env/lib/python3.5/site-packages/rinoh/reference.py", line 241, in split
    if section else None) or ''
  File "/tmp/env/lib/python3.5/site-packages/rinoh/reference.py", line 42, in get_id
    return self.id or document.ids_by_element[self]
AttributeError: 'TableOfContentsSection' object has no attribute 'ids_by_element'
```

**Comment by brechtm** [comment]
Seems this is fixed in master. The next release will be able to render even empty reStructuredText files.
