### ISSUE TITLE
'decoration' node is not yet supported (rinoh.frontend.rst.nodes)

### ISSUE THREAD

**Issue by cadu-leite** [brechtm/rinohtype#112]
I trying to convert from  `.rst` to `.pdf` 
recieve an error  `'decoration' node is not yet supported (rinoh.frontend.rst.nodes)`

but the `index.rst` file has this content.

```rst
.. contents::
.. section-numbering::
.. footer::

    Page: ###Page###/###Total###

                            # <=====  this is the line 17 - it is a blank line - at least before parsing 
.. toctree::
    :maxdepth: 2
    :caption: Contents:

    modules/models
```
 I'm not sure this is the wright error message. 

**IT WORKED** when I deleted the `footer` directive. 

It doe make sense? 

```bash
# Sphinx version: 1.6.5
# Python version: 3.6.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   index
#   
#   modules/models
#   
#   
#   
#   resolving references...
#   
#   rendering...
#   
# Loaded extensions:
#   alabaster (0.7.10) from /Envs/rinohtype/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.doctest (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.todo (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.imgmath (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.ifconfig (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.viewcode (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.githubpages (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/githubpages.py
#   sphinx.ext.graphviz (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (1.6.5) from /Envs/rinohtype/lib/python3.6/site-packages/sphinx/ext/inheritance_diagram.py
#   rinoh.frontend.sphinx (unknown version) from /Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/sphinx/__init__.py
#   sphinxjp.themes.basicstrap (unknown version) from /Envs/rinohtype/lib/python3.6/site-packages/sphinxjp/themes/basicstrap/__init__.py
Traceback (most recent call last):
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 27, in map_node
    return cls._mapping[node_name.replace('-', '_')](node)
KeyError: 'decoration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Envs/rinohtype/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Envs/rinohtype/lib/python3.6/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Envs/rinohtype/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 326, in build_update
    self.build(['__all__'], to_build)
  File "/Envs/rinohtype/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/sphinx/__init__.py", line 220, in write
    targetname)
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/sphinx/__init__.py", line 228, in write_doc
    rinoh_tree = parser.from_doctree(source_path, doctree)
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/rst/__init__.py", line 124, in from_doctree
    flowables = mapped_tree.children_flowables()
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 121, in children_flowables
    children = self.getchildren()[skip_first:]
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 63, in getchildren
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 63, in <listcomp>
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/Envs/rinohtype/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 32, in map_node
    cls.__module__))
NotImplementedError: /Volumes/p10G/prj/dj_datadictionary_testproject/docs/source/index.rst:17 the 'decoration' node is not yet supported (rinoh.frontend.rst.nodes)
```

**Comment by brechtm** [comment]
Thanks for reporting this bug!

The [decoration docutils node](http://docutils.sourceforge.net/docs/ref/doctree.html#decoration) is indeed not yet supported. It seems that `###Page###` and `###Total###` are [rst2pdf-specific magic tokens](https://ralsina.me/static/manual.pdf). This will not be supported by rinohtype. You should [configure your document template](http://www.mos6581.org/rinohtype/basicstyling.html#configuring-a-template) instead (setting [footer_text](http://www.mos6581.org/rinohtype/api/template.html#rinoh.template.PageTemplate.footer_text)).

I'm thinking of having rinohtype ignore the decoration (and header/footer) nodes and outputting a warning, directing the user to document templates.
