### ISSUE TITLE
Add support for Sphinx's add_node()

### ISSUE THREAD

**Issue by Divya063** [brechtm/rinohtype#118]
I'm trying to convert rst to pdf, we are having video directive which is implemented by one of the contributors in the documentation which is used as ` .. video:: path/to/video`. Is there any way I can suppress the error?
Here is the log.
```
# Sphinx version: 1.6.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   faq
#   
#   glossary
#   
#   
#   
#   resolving references...
#   
#   rendering...
#   
# Loaded extensions:
#   sphinx.ext.autodoc (1.6.1) from /home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.coverage (1.6.1) from /home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.todo (1.6.1) from /home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/ext/todo.py
#   sphinx.ext.doctest (1.6.1) from /home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/ext/doctest.py
#   alabaster (0.7.10) from /home/divya/odk/odkenv/lib/python3.5/site-packages/alabaster/__init__.py
#   video (unknown version) from /home/divya/odk/odkenv/docs/video.py
#   sphinx.ext.mathjax (1.6.1) from /home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/ext/mathjax.py
#   rinoh.frontend.sphinx (unknown version) from /home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/sphinx/__init__.py
#   sphinx.ext.intersphinx (1.6.1) from /home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/ext/intersphinx.py
Traceback (most recent call last):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 27, in map_node
    return cls._mapping[node_name.replace('-', '_')](node)
KeyError: 'video_node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/cmdline.py", line 307, in main
    return app.statuscode
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/util/docutils.py", line 48, in docutils_namespace
    yield
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 323, in build_update
    self.build(['__all__'], to_build)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/sphinx/__init__.py", line 220, in write
    targetname)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/sphinx/__init__.py", line 228, in write_doc
    rinoh_tree = parser.from_doctree(source_path, doctree)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 124, in from_doctree
    flowables = mapped_tree.children_flowables()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/sphinx/nodes.py", line 217, in build_flowable
    return super().build_flowable(id='%' + self.get('docname'), **kwargs)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/sphinx/nodes.py", line 217, in build_flowable
    return super().build_flowable(id='%' + self.get('docname'), **kwargs)
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 121, in children_flowables
    children = self.getchildren()[skip_first:]
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 63, in getchildren
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 63, in <listcomp>
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/home/divya/odk/odkenv/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 32, in map_node
    cls.__module__))
NotImplementedError: /home/divya/odk/odkenv/docs/src/collect-filling-forms.rst:None the 'video_node' node is not yet supported (rinoh.frontend.rst.nodes)
```

**Comment by brechtm** [comment]
A little detective work tells me you are trying to build the [docs for opendatakit](/opendatakit/docs)? The video directive is a custom one [defined in the project](/opendatakit/docs/pull/370) itself.

Have you tried adding support for rinoh in this definition? Adding
```
rinoh = (visit_video_nonhtml, depart_video_nonhtml),
```
to the `app.add_node` call at the bottom of `video.py` would perhaps be enough.

I haven't been able to try this myself because I have trouble checking out the repository (due to a Homebrew git issue in High Sierra).

**Comment by Divya063** [comment]
Thanks for looking into this issue! Yes, I'm trying to build the docs for Open Data Kit. I [added the lines](https://github.com/Divya063/docs/blob/75986ff7f03b0196733d36a6cfa8706b7d6039de/video.py#L147) but I'm getting the same error.
> I haven't been able to try this myself because I have trouble checking out the repository (due to a Homebrew git-lfs issue in High Sierra).

I was wondering what is the issue?

**Comment by brechtm** [comment]
I managed to fix the git-lfs issue (installed new version) and check out the Open Data Kit repository. Adding the lines as I suggested indeed does not work. You can add the following to `video.py` instead:

```
try:
    from rinoh.frontend.rst import DocutilsDummyNode

    class Video_Node(DocutilsDummyNode):
        pass
except ImportError:    # rinohtype is not installed
    pass
```

I will see if the `add_node` method can be made to work with rinohtype.

I also discovered opendatakit/docs#271. I'll look into the rinohtype issues reported there.

**Comment by brechtm** [comment]
`add_node` could be made to work for rinohtype. See sphinx-doc/sphinx#4643.

Work-in-progess: branch wip/sphinx_add_node

**Comment by brechtm** [comment]
Next step: test with Sphinx 1.8.0.

**Comment by calve** [comment]
I'm running into the same issue with a custom directive. None suggestions appears to work.

**Comment by vtexier** [comment]
I'm running into the same issue with the `plantuml` extension directive.
https://github.com/sphinx-contrib/plantuml/

**Comment by brechtm** [comment]
The problem is that Sphinx makes the assumption that all builders (including third-party builders) share the same architecture which makes use of a SphinxTranslator subclass that defines visit/depart methods for all node types. rinohtype doesn't use a translator with visit/depart methods for each node types, but instead relies on "translator" classes being defined for each of the node types.

Since the visit/depart methods that need to be passed to `add_node()` are output-format specific anyway, you might as well handle the rinoh-end of things by defining a custom translator class for your custom node. So for a new node type `mynode`, instead of adding `rinoh=(visit_mynode_nonhtml, depart_mynode_nonhtml)` to the `add_node` call, you should define a `MyNode` class. In the case that nodes of this type may be skipped in the rinohtype output, simply subclass `DocutilsDummyNode`:
```
try:
    from rinoh.frontend.rst import DocutilsDummyNode

    class MyNode(DocutilsDummyNode):    # class name matches "mynode"
        pass
except ImportError:    # do nothing when rinohtype is not installed
    pass
```

Making rinohtype output something involves more work of course. I'm happy to help with that, however.

@calve My apologies for the long delay. If this is still relevant for you, can you provide more context?

@vtexier If you are comfortable with Python programming, you can take inspiration from [latex_visit_plantuml](https://github.com/sphinx-contrib/plantuml/blob/b4916f96848bfbbb2a301570025f7de9489d8e60/sphinxcontrib/plantuml.py#L423) to create the `PlantUML` translator class. rinohtype supports PNG and PDF images. Here's a start with rinohtype specifics:

```
from rinoh import Image
from rinoh.frontend.rst import DocutilsBodyNode
from rinoh.frontend.rst.nodes import convert_quantity

class PlantUML(DocutilsBodyNode):
    def build_flowable(self):
        # TODO: generate image
        image_path = ...
        width_string = self.get('width')
        align = self.get('align')
        return Image(image_path, scale=self.get('scale', 100) / 100,
                     width=convert_quantity(width_string), align=align)
```

**Comment by calve** [comment]
> @calve My apologies for the long delay. If this is still relevant for you, can you provide more context?

Been a while :grin: I have this custom directive that allow to insert arbitrary script tags when rendering to HTML.

The following code appears to work;

 - actually insert `<script>` tags when rendering to HTML
 - insert some placeholder when rendering to PDF

```python
"""
Custom directive to include raw javascript

Usage:

    .. js:: ./path/to/file.js

"""
from docutils.parsers.rst import Directive, directives
from docutils import nodes
from pathlib import Path
from rinoh import CodeBlock
from rinoh.frontend.rst import DocutilsBodyNode

class RinohJs(DocutilsBodyNode):
    node_name = 'js'

    def build_flowable(self):
        return CodeBlock("Cannot render a script tag in a pdf build", style="js")


class js(nodes.General, nodes.Inline, nodes.Element):
    pass

class JsDirective(Directive):
    optional_arguments = 1
    option_spec = {'path': directives.path}

    def run(self):
        node = js()
        src_dir = Path(self.state.document.settings.env.srcdir)
        with (src_dir / self.arguments[0]).open() as _f:
            node['content'] = _f.read()
        return [node]


def html_visit_js(self, node):
    self.body.append("<script>" + node['content'] + "</script>")


def html_departure_js(self, node):
    pass


def null_visit_js(self, node):
    pass


def setup(app):
    app.add_node(js,
                 html=(html_visit_js, html_departure_js),
                 latex=(null_visit_js, None),
                 texinfo=(null_visit_js, None),
                 text=(null_visit_js, None),
                 man=(null_visit_js, None))
    app.add_directive('js', JsDirective)
    return
```
