### ISSUE TITLE
Can't get manual DocumentTree example to work

### ISSUE THREAD

**Issue by justvanrossum** [brechtm/rinohtype#139]
I'm trying to use the example at http://www.mos6581.org/rinohtype/quickstart.html, under "Here is an example document tree of a short article:", and extend it with the lines:

```python
from rinoh.templates import Article
document = Article(document_tree)
document.render('my_document')
```

But this gives me the following traceback:

```
Traceback (most recent call last):
  File "frontendtest.py", line 40, in <module>
    document.render('my_document')
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 434, in render
    self.prepare(fake_container)
  File "/Users/just/code/git/rinohtype/src/rinoh/template.py", line 675, in prepare
    part_template.prepare(flowable_target)
  File "/Users/just/code/git/rinohtype/src/rinoh/template.py", line 331, in prepare
    flowable.prepare(fake_container)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 557, in prepare
    flowable.prepare(flowable_target)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 557, in prepare
    flowable.prepare(flowable_target)
  File "/Users/just/code/git/rinohtype/src/rinoh/structure.py", line 159, in prepare
    title_string = self.content.to_string(flowable_target)
AttributeError: 'str' object has no attribute 'to_string'
```

The error happens with a `Heading` flowable.

If I change the text of the Headings like so:

`Heading(MixedStyledText('First Section'))`

I get the following traceback:

```
Traceback (most recent call last):
  File "frontendtest.py", line 40, in <module>
    document.render('my_document')
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 437, in render
    self.part_page_counts = self._render_pages()
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 505, in _render_pages
    part_page_count += part.render(part_page_count.count + 1)
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 229, in render
    page.render()
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 161, in render
    super().render(CONTENT, rerender=index > 0)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 186, in render
    child.render(type, rerender)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 186, in render
    child.render(type, rerender)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 289, in render
    self._render(type, rerender)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 341, in _render
    self.chain.render(self, rerender=rerender)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 588, in render
    state=self._state)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 199, in flow
    state=state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 251, in flow_inner
    space_below=space_below, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 464, in render
    **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 493, in _flow_with_next
    state=state.first_flowable_state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 199, in flow
    state=state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 251, in flow_inner
    space_below=space_below, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 464, in render
    **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 493, in _flow_with_next
    state=state.first_flowable_state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 819, in flow
    return super().flow(container, last_descender, state)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 199, in flow
    state=state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 251, in flow_inner
    space_below=space_below, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 464, in render
    **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 501, in _flow_with_next
    descender, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 493, in _flow_with_next
    state=state.first_flowable_state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 199, in flow
    state=state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 251, in flow_inner
    space_below=space_below, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 665, in render
    word = state.next_word()
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 572, in next_word
    word = next(self._words)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 505, in spans_to_words
    span = next(spans)
  File "/Users/just/code/git/rinohtype/src/rinoh/text.py", line 392, in spans
    for span in child.spans(container):
  File "/Users/just/code/git/rinohtype/src/rinoh/text.py", line 392, in spans
    for span in child.spans(container):
  File "/Users/just/code/git/rinohtype/src/rinoh/text.py", line 283, in spans
    raise NotImplementedError
NotImplementedError
```

And now I am stuck. Is there anything that I'm missing in how I use the example?

**Comment by brechtm** [comment]
Possibly things have changed to break things example, or perhaps it never worked :-)
This version should work:

```
from rinoh.document import DocumentTree
from rinoh.styleds import *
from rinoh.templates import Article

document_tree = DocumentTree(
                    [Paragraph('My Document', style='title'), # metadata!
                     Section([Heading(SingleStyledText('First Section')),
                              Paragraph('This is a paragraph with some '
                                        + SingleStyledText('emphasized text',
                                                           style='emphasis')
                                        + ' and an '
                                        + InlineImage('image.pdf')),
                              Section([Heading(SingleStyledText('A subsection')),
                                       Paragraph('Another paragraph')
                                      ])
                             ]),
                     Section([Heading(SingleStyledText('Second Section')),
                              List([Paragraph('a list item'),
                                    Paragraph('another list item')
                                   ])
                             ])
                    ])

document = Article(document_tree)
document.render('my_document')
```

This works with the master branch of rinohtype. I recommend running a checkout of the git master branch, as the last release is unfortunately quite outdated. I plan on making a new release soon.

**Comment by justvanrossum** [comment]
Thanks, that works! (Yeah, I run from the git master.)
