### ISSUE TITLE
[opentype] Traceback when using a font that contains lookups unsupported by rinoh

### ISSUE THREAD

**Issue by justvanrossum** [brechtm/rinohtype#141]
I don't currently need this particular lookup ("6: ChainingContextSubtable"), but it would be nice if rinoh could simply ignore this lookup instead of aborting with a traceback. I tried implementing that, but I run into deeper errors.

```
Traceback (most recent call last):
  File "/Users/just/code/git/rinohtype/src/rinoh/util.py", line 137, in function_wrapper
    return cache[args_kwargs]
KeyError: (<rinoh.font.GlyphMetrics object at 0x10a878cf0>, <rinoh.font.GlyphMetrics object at 0x10a89fe58>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frontendtest.py", line 40, in <module>
    document.render('my_document')
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 437, in render
    self.part_page_counts = self._render_pages()
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 505, in _render_pages
    part_page_count += part.render(part_page_count.count + 1)
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 229, in render
    page.render()
  File "/Users/just/code/git/rinohtype/src/rinoh/document.py", line 161, in render
    super().render(CONTENT, rerender=index > 0)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 186, in render
    child.render(type, rerender)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 289, in render
    self._render(type, rerender)
  File "/Users/just/code/git/rinohtype/src/rinoh/layout.py", line 316, in _render
    self.flowables.flow(self, last_descender=None)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 199, in flow
    state=state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 251, in flow_inner
    space_below=space_below, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 464, in render
    **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 493, in _flow_with_next
    state=state.first_flowable_state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 199, in flow
    state=state, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/flowable.py", line 251, in flow_inner
    space_below=space_below, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 665, in render
    word = state.next_word()
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 572, in next_word
    word = next(self._words)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 531, in spans_to_words
    glyphs_and_widths = lig_kern(part, glyphs)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 404, in lig_kern
    for char, glyph, kern_adjust in glyphs_kern]
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 403, in <listcomp>
    return [Glyph(glyph, scale * (glyph.width + kern_adjust), char)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 376, in kern
    prev_char, prev_glyph = next(chars_and_glyphs)
  File "/Users/just/code/git/rinohtype/src/rinoh/paragraph.py", line 365, in form_ligatures
    ligature_glyph = get_ligature(prev_glyph, glyph)
  File "/Users/just/code/git/rinohtype/src/rinoh/util.py", line 139, in function_wrapper
    cache_value = function(obj, *args, **kwargs)
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/__init__.py", line 145, in get_ligature
    lookup_tables = self._get_lookup_tables('GSUB', 'liga', 'latn')
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/__init__.py", line 139, in _get_lookup_tables
    for lookup_list_index in lookup_list_indices]
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/__init__.py", line 139, in <listcomp>
    for lookup_list_index in lookup_list_indices]
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/layout.py", line 163, in __getitem__
    self[index] = self._reader(self._file, self._offsets[index])
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/layout.py", line 174, in <lambda>
    types)
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/layout.py", line 142, in __init__
    for subtable_offset in offsets]
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/layout.py", line 142, in <listcomp>
    for subtable_offset in offsets]
  File "/Users/just/code/git/rinohtype/src/rinoh/font/opentype/gsub.py", line 128, in __init__
    subtable_class = GsubTable.lookup_types[self['ExtensionLookupType']]
KeyError: 6
```

The font in question is Brill Roman, from https://brill.com/page/290?lang=en.

**Comment by justvanrossum** [comment]
Btw. implementing #137 would resolve this issue in a much more fundamental way.

**Comment by brechtm** [comment]
> I tried implementing that, but I run into deeper errors.

I have fixed another issue that prevented loading the Brill font in 05c567aee9586499ac4427c1d24b38213758d85d.
