### ISSUE TITLE
Exception occurred

### ISSUE THREAD

**Issue by nikkk91** [brechtm/rinohtype#153]
I try to make rinoh with Sphinx but I receive this error:
```
line 261, in flow_inner
    padded_width = content_width + padding_h
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Can you help me?

For claryfing I report the full prompt messages and log error:

```
C:\Sphinx>make rinoh
Running Sphinx v2.4.4
'rinoh_documents' config variable not set, automatically converting from 'latex_documents'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
loading pickled environment... 'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
done
building [mo]: targets for 0 po files that are out of date
building [rinoh]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing output... index sector sectors/conechannelsector sectors/flangesector tool tools/generic tools/anisometric example resolving references...
rendering...
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
rinohtype 0.4.0 (2020-03-05)  Copyright (c) Brecht Machiels
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
TeX Gyre Pagella does not include a normal medium upright font. Falling back to normal regular upright
 32% [============                            ] ETA 00:07 (00:03) page 3
Exception occurred:
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 261, in flow_inner
    padded_width = content_width + padding_h
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
The full traceback has been saved in C:\Users\admin\AppData\Local\Temp\sphinx-err-nb0pwxmm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

And this is the log:
```
# Sphinx version: 2.4.4
# Python version: 3.8.2 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   index
#   sector
#   sectors/conechannelsector
#   sectors/flangesector
#   tool
#   tools/generic
#   tools/anisometric
#   example
#   resolving references...
#   rendering...
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\alabaster\__init__.py
#   rinoh.frontend.sphinx (0.4.0) from c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\frontend\sphinx\__init__.py
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinx\application.py", line 349, in build
    self.builder.build_update()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinx\builders\__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\sphinx\builders\__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\frontend\sphinx\__init__.py", line 222, in write
    self.write_doc(docname, doctree, docnames, targetname)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\frontend\sphinx\__init__.py", line 242, in write_doc
    rinoh_document.render(outfilename)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\document.py", line 348, in render
    self.part_page_counts = self._render_pages()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\document.py", line 416, in _render_pages
    part_page_count += part.render(part_page_count.count + 1)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\template.py", line 385, in render
    page.render()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\document.py", line 158, in render
    super().render(CONTENT, rerender=index > 0)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\layout.py", line 186, in render
    child.render(type, rerender)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\layout.py", line 186, in render
    child.render(type, rerender)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\layout.py", line 287, in render
    self._render(type, rerender)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\layout.py", line 339, in _render
    self.chain.render(self, rerender=rerender)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\layout.py", line 589, in render
    self.flowables.flow(container, last_descender=None,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 829, in flow
    return super().flow(container, last_descender, state)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 829, in flow
    return super().flow(container, last_descender, state)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 829, in flow
    return super().flow(container, last_descender, state)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 250, in flow_inner
    self.render(pad_cntnr, descender, state=state,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 468, in render
    self._flow_with_next(state, container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 509, in _flow_with_next
    width, _, descender = self._flow_with_next(state, container,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 500, in _flow_with_next
    flowable.flow(maybe_container, descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 196, in flow
    self.flow_inner(margin_container, last_descender,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\rinoh\flowable.py", line 261, in flow_inner
    padded_width = content_width + padding_h
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by brechtm** [comment]
Can you share the Sphinx project that triggers this bug? If that's not possible, can you try to provide a minimal project that shows the same issue? Thanks.

**Comment by nikkk91** [comment]
[SphinxError.zip](https://github.com/brechtm/rinohtype/files/4475205/SphinxError.zip)

Attached you can find the project that returns the error.

**Comment by brechtm** [comment]
Thanks. This will be fixed in the next release. In the meantime, you can install rinohtype from the master branch.

P.S. Your project uncovered another bug (#154).
