### ISSUE TITLE
AttributeError: No such document option: page_size

### ISSUE THREAD

**Issue by takuan-osho** [brechtm/rinohtype#16]
rinohtype raised an AttributeError when I did `rinoh demo.txt`.
demo.txt comes from [tutorial texts](http://docutils.sourceforge.net/docs/user/rst/demo.txt).

```bash
Traceback (most recent call last):
  File "/Users/taku/dev/src/github.com/brechtm/rinohtype/venv/bin/rinoh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/taku/dev/src/github.com/brechtm/rinohtype/bin/rinoh", line 5, in <module>
    main()
  File "/Users/taku/dev/src/github.com/brechtm/rinohtype/rinoh/tool.py", line 89, in main
    options = ArticleOptions(page_size=page_size)
  File "/Users/taku/dev/src/github.com/brechtm/rinohtype/rinoh/template.py", line 248, in __init__
    raise AttributeError('No such document option: {}'.format(name))
AttributeError: No such document option: page_size
```

**Comment by brechtm** [comment]
This is from a somewhat recent version from the master branch, I assume? The document templates were (and are being) heavily reworked, breaking the ´rinoh´ tool. This shoud be fixed in the next release, due soon (hopefully a couple of weeks).

**Comment by takuan-osho** [comment]
Yes, I cloned this master branch yesterday.

I'm looking forward to the next release of rinohtype.
