### ISSUE TITLE
get_reference() KeyError in document.py

### ISSUE THREAD

**Issue by maltfield** [brechtm/rinohtype#174]
I encountered this error

```
Exception occurred:
  File "/usr/local/lib/python3.7/dist-packages/rinoh/document.py", line 287, in get_reference
    return self.references[id][reference_type]
KeyError: '%software_usr/gui#id1'
```

From the following contents of a sphinx `.rst` [source file](https://raw.githubusercontent.com/BusKill/buskill-app/6622b0e53495886d7a89522f9155aef09d12675f/docs/software_usr/gui.rst):

```
.. list-table::

        * - .. figure:: /images/buskill_app_lin_disarmed1.jpg
                :alt: screenshot of the buskill-app repo home page
                :align: center

                Linux
          - .. figure:: /images/buskill_app_win_disarmed1.jpg
                :alt: screenshot of the buskill-app repo home page
                :align: center

                Windows
          - .. figure:: /images/buskill_app_mac_disarmed1.jpg
                :alt: screenshot of the buskill-app repo home page
                :align: center

                MacOS
```

# System Info

```
user@disp4821:~/buskill-app$ cat /etc/issue
Debian GNU/Linux 10 \n \l

user@disp4821:~/buskill-app$ uname -a
Linux disp4821 4.19.125-1.pvops.qubes.x86_64 #1 SMP Sat May 30 16:11:30 UTC 2020 x86_64 GNU/Linux
user@disp4821:~/buskill-app$ python3 -m pip list | grep rinoh
rinoh-typeface-dejavuserif    0.1.1        
rinoh-typeface-texgyrecursor  0.1.1        
rinoh-typeface-texgyreheros   0.1.1        
rinoh-typeface-texgyrepagella 0.1.1        
rinohtype                     0.4.2        
user@disp4821:~/buskill-app$ dpkg -l | grep sphinx
ii  libjs-sphinxdoc                       1.8.4-1                             all          JavaScript support for Sphinx documentation
ii  python3-sphinx                        1.8.4-1                             all          documentation generator for Python projects (implemented in Python 3)
ii  python3-sphinx-rtd-theme              0.4.3+dfsg-1                        all          sphinx theme from readthedocs.org (Python 3)
ii  sphinx-common                         1.8.4-1                             all          documentation generator for Python projects - common data
ii  sphinx-rtd-theme-common               0.4.3+dfsg-1                        all          sphinx theme from readthedocs.org (common files)
user@disp4821:~/buskill-app$ 
```

# Steps to reproduce

```
git clone https://github.com/BusKill/buskill-app.git
cd buskill-app
git reset --hard 6622b0e53495886d7a89522f9155aef09d12675f
sphinx-build -b rinoh docs/ docs/_build/rinoh -D language=en
```

## Example execution

```
user@disp4821:~$ git clone https://github.com/BusKill/buskill-app.git
Cloning into 'buskill-app'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 2294 (delta 25), reused 37 (delta 20), pack-reused 2246
Receiving objects: 100% (2294/2294), 197.21 MiB | 101.00 KiB/s, done.
Resolving deltas: 100% (1135/1135), done.
Checking out files: 100% (136/136), done.
user@disp4821:~$ cd buskill-app
user@disp4821:~/buskill-app$ git reset --hard 6622b0e53495886d7a89522f9155aef09d12675f
HEAD is now at 6622b0e finished quickstart guide in docs
user@disp4821:~/buskill-app$ 

user@disp4821:~/buskill-app$ sphinx-build -b rinoh docs/ docs/_build/rinoh -D language=en
Running Sphinx v1.8.4
loading translations [en]... done
making output directory...
'rinoh_documents' config variable not set, automatically converting from 'latex_documents'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
building [mo]: targets for 0 po files that are out of date
building [rinoh]: all documents
updating environment: 31 added, 0 changed, 0 removed
reading sources... [100%] support                                               
/home/user/buskill-app/docs/hardware_dev/bom.rst:16: WARNING: Indirect hyperlink target "amazon"  refers to target "carabiner1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:18: WARNING: Indirect hyperlink target "amazon"  refers to target "usbadrive1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:20: WARNING: Indirect hyperlink target "amazon"  refers to target "usba3mextension1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:23: WARNING: Indirect hyperlink target "amazon"  refers to target "usbamagneticbreakaway1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:43: WARNING: Indirect hyperlink target "amazon"  refers to target "carabiner1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:45: WARNING: Indirect hyperlink target "amazon"  refers to target "usbcdrive1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:47: WARNING: Indirect hyperlink target "amazon"  refers to target "usbc3mextension1", which does not exist.
/home/user/buskill-app/docs/hardware_dev/bom.rst:50: WARNING: Indirect hyperlink target "amazon"  refers to target "usbcmagneticbreakaway1", which does not exist.
/home/user/buskill-app/docs/introduction/faq.rst:4: WARNING: Duplicate explicit target name: "buskill".
looking for now-outdated files... none found
pickling environment... 'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
done
checking consistency... done
processing target... index introduction/index introduction/what introduction/quickstart introduction/faq hardware_usr/index software_usr/index software_usr/requirements software_usr/download software_usr/signature software_usr/execute software_usr/gui software_usr/cli hardware_dev/index hardware_dev/bom hardware_dev/assembly software_dev/index software_dev/autodoc software_dev/build software_dev/documentation software_dev/release security/index security/infrastructure security/pgpkeys security/tradeoffs security/reporting support contributing changelog license attribution resolving references...
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
rendering... 
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
rinohtype 0.4.2 (2020-07-28)  Copyright (c) Brecht Machiels
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
TeX Gyre Pagella does not include a normal medium upright font. Falling back to normal regular upright
[table of contents] Cannot reference "1" (page i)
[table of contents] Cannot reference "3" (page ii)
[table of contents] Cannot reference "4" (page ii)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x2708 (✈)e 4
DejaVuSerif-Bold does not contain glyph for unicode index 0x2708 (✈)
TeXGyreHeros-Bold does not contain glyph for unicode index 0xfe0f (️)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x1f399 (🎙) 4
DejaVuSerif-Bold does not contain glyph for unicode index 0x1f399 (🎙)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x262e (☮)e 4
DejaVuSerif-Bold does not contain glyph for unicode index 0x262e (☮)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x20bf (₿)e 4
DejaVuSerif-Bold does not contain glyph for unicode index 0x20bf (₿)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x1f4bc (💼)5
DejaVuSerif-Bold does not contain glyph for unicode index 0x1f4bc (💼)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x1f575 (🕵) 5
DejaVuSerif-Bold does not contain glyph for unicode index 0x1f575 (🕵)
TeX Gyre Cursor does not include a normal medium upright font. Falling back to normal regular upright
 33% [=============                           ] ETA 00:21 (00:10) page 19
Exception occurred:
  File "/usr/local/lib/python3.7/dist-packages/rinoh/document.py", line 287, in get_reference
    return self.references[id][reference_type]
KeyError: '%software_usr/gui#id1'
The full traceback has been saved in /tmp/sphinx-err-cg2ogwkt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
user@disp4821:~/buskill-app$ 
```

**Comment by maltfield** [comment]
I did try to get the latest version from master, but the install failed. It might be failing because I have a spotty internet connection, but it's not worth retrying downloading >100M files if they're just going to timeout and delete their cache such that a retrying is going to have to re-download fresh rather than continuing where it left off..

```
root@disp4821:~# pip3 install git+https://github.com/brechtm/rinohtype.git@master
Collecting git+https://github.com/brechtm/rinohtype.git@master
  Cloning https://github.com/brechtm/rinohtype.git (to revision master) to /tmp/pip-req-build-gsuzog_i


  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gsuzog_i/setup.py", line 105, in <module>
        version=get_version(),
      File "/tmp/pip-req-build-gsuzog_i/setup.py", line 52, in get_version
        assert False
    AssertionError
    ?? pip-delete-this-directory.txt
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-gsuzog_i/
root@disp4821:~# 
```

**Comment by maltfield** [comment]
I simplified the source `.rst` file to be this, which fails:

```
.. list-table::

   * - .. figure:: /images/buskill_app_lin_disarmed1.jpg
		
        Caption
```

While this succeeds.

```
.. list-table::

   * - .. figure:: /images/buskill_app_lin_disarmed1.jpg
		
```

So it appears to be something related to the `figure` directive's contents (ie the caption).

**Comment by brechtm** [comment]
Hi Michael. Thanks for another detailed bug report!
