### ISSUE TITLE
Developer instructions lead to failed test run

### ISSUE THREAD

**Issue by bignose-debian** [brechtm/rinohtype#177]
The `DEVELOPER` document is not clear on how to run the test suite, but it contains this:

> This project makes use of tox_ to manage running tests and other tasks. The
> tests can be divided into three categories: checks, unit tests and regression
> tests. ``tox.ini`` defines "environments" that configure these tasks. Each of
> these are described below. The unit and integration tests make use of the
> pytest_ framework.

When I install and run `tox` using standard commands:

```
$ python3 -m pip install tox pytest
$ python3 -m tox py38
```

the test run fails:

```
$ python3 -m tox -e py38
GLOB sdist-make: /home/bignose/Projects/python/rinohtype/devel/setup.py
py38 inst-nodeps: /home/bignose/Projects/python/rinohtype/devel/.tox/.tmp/package/1/rinohtype-0.4.3.dev0+4c771275.zip
py38 installed: alabaster==0.7.12,attrs==20.2.0,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,commonmark==0.9.1,coverage==5.2.1,docutils==0.16,idna==2.10,imagesize==1.2.0,iniconfig==1.0.1,Jinja2==2.11.2,MarkupSafe==1.1.1,more-itertools==8.5.0,packaging==20.4,pluggy==0.13.1,py==1.9.0,Pygments==2.6.1,pyparsing==2.4.7,pytest==6.0.1,pytest-cov==2.10.1,pytz==2020.1,recommonmark==0.6.0,requests==2.24.0,rinoh-typeface-dejavuserif==0.1.1,rinoh-typeface-texgyrecursor==0.1.1,rinoh-typeface-texgyreheros==0.1.1,rinoh-typeface-texgyrepagella==0.1.1,rinohtype @ file:///home/bignose/Projects/python/rinohtype/devel/.tox/.tmp/package/1/rinohtype-0.4.3.dev0%2B4c771275.zip,six==1.15.0,snowballstemmer==2.0.0,Sphinx==3.2.1,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==1.0.3,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.4,toml==0.10.1,urllib3==1.25.10
py38 run-test-pre: PYTHONHASHSEED='173854183'
py38 run-test: commands[0] | python run_tests.py tests
================================================ test session starts =================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
rootdir: /home/bignose/Projects/python/rinohtype/devel, configfile: setup.cfg
plugins: cov-2.10.1
collected 76 items

tests/test_color.py ......                                                                                     [  7%]
tests/test_dimension.py ............                                                                           [ 23%]
tests/test_font.py .
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 240, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 296, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 321, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/warnings.py", line 163, in pytest_runtest_protocol
INTERNALERROR>     yield
INTERNALERROR>   File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
INTERNALERROR>     next(self.gen)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/warnings.py", line 135, in catch_warnings_for_item
INTERNALERROR>     ihook.pytest_warning_recorded.call_historic(
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/terminal.py", line 493, in pytest_warning_recorded
INTERNALERROR>     message = warning_record_to_str(warning_message)
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/_pytest/warnings.py", line 148, in warning_record_to_str
INTERNALERROR>     msg = warnings.formatwarning(
INTERNALERROR>   File "/home/bignose/Projects/python/rinohtype/devel/.tox/py38/lib/python3.8/site-packages/rinoh/warnings.py", line 28, in formatwarning
INTERNALERROR>     return '{}\n'.format(warning.message)
INTERNALERROR> AttributeError: 'str' object has no attribute 'message'

================================================= 19 passed in 0.44s =================================================
ERROR: InvocationError for command /home/bignose/Projects/python/rinohtype/devel/.tox/py38/bin/python run_tests.py tests (exited with code 3)
______________________________________________________ summary _______________________________________________________
ERROR:   py38: commands failed
```

I think this means the `setup.py` dependencies are not sufficiently specified to get the Tox test run to succeed.

**Comment by brechtm** [comment]
I saw this issue yesterday as well with tests running on Travis as well. This seems to be due to a change introduced with pytest 6.0.0. If you want, you're welcome to figure out what's causing this and submit a fix (to rinohtype or pytest). Otherwise, install pytest 5.4.3 for now to sidestep this issue.

**Comment by bignose-debian** [comment]
> This seems to be due to a change introduced with pytest 6.0.0. […] Otherwise, install pytest 5.4.3 for now to sidestep this issue.

I have modified the developer instructions and Tox configuration to accommodate this; see the branch https://git.sr.ht/~bignose/RinohType/tree/issue/177/refine-requirements-and-instructions in my personal fork repository. That should merge cleanly to ‘master’ now.

With those changes, I do get the test suite to run successfully. Thanks!

**Comment by brechtm** [comment]
Thanks for the patch!

I have managed to fix the issue with pytest, so forcing the pytest version is no longer necessary.

I now understand your comment about the developer instructions not being clear. Later in DEVELOPING.rst, the use of [Poetry](https://python-poetry.org) is mentioned. I would like to point contributors to setting up a development environment using Poetry instead at the top of DEVELOPING.rst, inspired by your patch.

Requiring Poetry, pyenv and the set of Python versions presents quite a threshold to contributors however, so it would perhaps be good to also offer instructions on getting a simple development environment set up based on whatever Python version the user has installed. Toughts?

PS. When you want to submit a patch, please do this using a GitHub pull request. This makes sure that all contributors sign the [contributor license agreement](/brechtm/rinohtype/blob/master/CONTRIBUTING.rst#contributor-license-agreement).

**Comment by brechtm** [comment]
I've recently converted from setuptools to Poetry and updated the developer instructions to reflect that. It should also be less overwhelming to newcomers.
