### ISSUE TITLE
Is there any way to register a custom sphinx directive with rinoh? 

### ISSUE THREAD

**Issue by BenMemberg** [brechtm/rinohtype#201]
Our project defines a custom sphinx directive as per [this documentation](https://www.sphinx-doc.org/en/master/development/index.html). But this node type is not recognized by the rinoh sphinx builder, and errors when we run `make rinoh` with this error: 

```
# Sphinx version: 3.0.3
# Python version: 3.6.8 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   portal
#   
#   middleware
#   
#   backend
#   
#   resolving references...
#   
#   rendering...
#   
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.coverage (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.napoleon (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.doctest (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (3.0.3) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx_git (unknown version) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx_git/__init__.py
#   docxbuilder (unknown version) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/docxbuilder/__init__.py
#   recommonmark (0.6.0) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/recommonmark/__init__.py
#   compliance-control (0.1) from /Users/ben/source/sphinx/common/compliance-control.py
#   rinoh.frontend.sphinx (0.4.0) from /Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/sphinx/__init__.py
Traceback (most recent call last):
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 29, in map_node
    return cls._mapping[node_name.replace('-', '_')](node)
KeyError: 'ComplianceControl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/sphinx/__init__.py", line 222, in write
    self.write_doc(docname, doctree, docnames, targetname)
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/sphinx/__init__.py", line 228, in write_doc
    rinoh_tree = parser.from_doctree(doctree['source'], doctree)
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/rst/__init__.py", line 125, in from_doctree
    flowables = mapped_tree.children_flowables()
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 123, in children_flowables
    children = self.getchildren()[skip_first:]
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 65, in getchildren
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 65, in <listcomp>
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/Users/ben/.virtualenvs/sphinx/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 34, in map_node
    cls.__module__))
NotImplementedError: None:None the 'ComplianceControl' node is not yet supported (rinoh.frontend.rst.nodes)
```

So is there any supported way to register a custom sphinx directive with rinoh? Or if there is not currently, then is there any plan to add this functionality? Thanks!

**Comment by brechtm** [comment]
You have two options:

1. If possible, you can make your directive independent of the builder by implementing it using only built-in docutils nodes. For example, the directives provided by sphinxcontrib-drawio [inherit from the standard _image_ and _figure_ directives](https://github.com/Modelmat/sphinxcontrib-drawio/blob/3b8df70cf0f40f8571872e9016a696be2cfa3399/sphinxcontrib/drawio/__init__.py#L112) which simply modify the image/figure nodes returned.

2. rinohtype doesn't use _visit_/_depart_ methods to process the different types of docutils nodes. Instead, you need to define a "translator" class. See https://github.com/brechtm/rinohtype/issues/118#issuecomment-613582610 for more information. Note that rinohtype assumes docutils node classes to be lowercase, so in your case, you need to explicitly set the `node_name` class attribute:

    ```
    from rinoh import Paragraph
    from rinoh.frontend.rst.nodes import DocutilsBodyNode

    class RinohComplianceControl(DocutilsBodyNode):
        node_name = 'ComplianceControl'

        def build_flowable(self):
            ...
            return Paragraph(..., style='compliance-control')

    ```

    Alternatively, you can rename your docutils node class to _compliance_control_ and use _Complicance_Control_ instead of _RinohComplianceControl_ for the translator class.

Option 2 here requires you to build the rinohtype nodes yourself. You'll need to reference [frontend/rst/nodes.py](https://github.com/brechtm/rinohtype/blob/d15d725d54f57d13e712b744ca0cb60192db125b/src/rinoh/frontend/rst/nodes.py) for examples on how how to do this. But I highly recommend you go for option 1 instead, which will also save you work when you need to support another builder later on.

Looking at the [TODO extension example](https://www.sphinx-doc.org/en/master/development/tutorials/todo.html) in the Sphinx documentation, I feel that the implementation could be better. The extension is essentially independent of the builder, yet it makes use of _visit_/_depart_todo_node_ functions which simply forward to _visit_/_depart_admonition_. These could probably be replaced with something that would work for all builders, but I have not looking into this further.

**Comment by BenMemberg** [comment]
Thanks for the quick reply! 

I looked into your first suggestion and it seems in the linked DrawIO example, both the image and figure custom DrawIO directives extend a base class (DrawIOBase) that extends from the Sphinx directive class (SphinxDirective). They are then registered to sphinx within the setup class at the bottom of the file, the same as in the Sphinx TODO extension example. So these directives are not independent of the sphinx builder, unless I misunderstand the code. Is there another example of this strategy of using only docutils directives?  

For your second suggestion, would this require replacing our existing node types with subclasses of the DocutilsBodyNode class? And would these nodes work similarly to basic docutils nodes?

**Comment by brechtm** [comment]
My wording might have been somewhat confusing. There will always be a builder, of course. I meant to say that you can make your directive independent of the _specific_ builder being used. In practice, that means avoiding passing builder-specific visit/depart methods to [add_node(https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_node)]. For example, in the TODO extension example:

```python
def setup(app):
    ...
    app.add_node(todolist)
    app.add_node(todo,
                 html=(visit_todo_node, depart_todo_node),
                 latex=(visit_todo_node, depart_todo_node),
                 text=(visit_todo_node, depart_todo_node))
    ...
```

The _todolist_ node here is builder-independent but the _todo_ node isn't. The _todolist_ node is replaced with standard docutils nodes in _process_todo_nodes_. The _todo_ node could be handled in a similar way.

**Comment by brechtm** [comment]
Closing due to inactivity. Don't hesitate to add comments though.
