### ISSUE TITLE
rinohtype support for math

### ISSUE THREAD

**Issue by nworbmot** [brechtm/rinohtype#94]
I'm experimenting with using rinohtype to compile the documentation of the PyPSA software https://github.com/FRESNA/PyPSA project to PDF, because the standard sphinx latex build doesn't split long tables across multiple tables (see http://pypsa.org/doc/PyPSA.pdf).

However, rinohtype is throwing an error when I execute sphinx-build -b rinoh . _build/rinoh:

Exception occurred:
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 32, in map_node
    cls.__module__))
NotImplementedError: None:None the 'math' node is not yet supported (rinoh.frontend.rst.nodes)

Is math really not supported? If it is not supported, is it a future planned feature?
Many thanks for your help!
Tom

Here is the detailed log:

# Sphinx version: 1.5.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   troubleshooting
#   unit_testing
#   todo
#   comparable_software
#   developers
#   release_notes
#   mailing_list
#   
#   resolving references...
#   rendering...
# Loaded extensions:
#   sphinx.ext.imgmath (1.5.1) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.autodoc (1.5.1) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/ext/autodoc.py
#   sphinx.domains.cpp (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/domains/cpp.py
#   sphinx.builders.linkcheck (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/linkcheck.py
#   sphinx.builders.manpage (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/manpage.py
#   sphinx.ext.todo (1.5.1) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/ext/todo.py
#   rinoh.frontend.sphinx (unknown version) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/sphinx/__init__.py
#   sphinx.builders.latex (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/latex.py
#   sphinx.builders.epub3 (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/epub3.py
#   alabaster (0.7.9) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinx.domains.javascript (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/domains/javascript.py
#   sphinx.builders.devhelp (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/devhelp.py
#   sphinx.directives (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/directives/__init__.py
#   sphinx.roles (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/roles.py
#   sphinx.builders.qthelp (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/qthelp.py
#   sphinx.domains.c (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/domains/c.py
#   sphinx.directives.other (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/directives/other.py
#   sphinx.ext.intersphinx (1.5.1) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/ext/intersphinx.py
#   sphinx.directives.patches (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/directives/patches.py
#   sphinx.builders.texinfo (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/texinfo.py
#   sphinx.directives.code (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/directives/code.py
#   sphinx.builders.websupport (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/websupport.py
#   sphinx.builders.applehelp (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/applehelp.py
#   sphinx.builders.xml (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/xml.py
#   sphinx.builders.changes (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/changes.py
#   sphinx.domains.std (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/domains/std.py
#   sphinx.domains.rst (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/domains/rst.py
#   sphinx.builders.htmlhelp (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/htmlhelp.py
#   sphinx.domains.python (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/domains/python.py
#   sphinx.builders.dummy (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/dummy.py
#   sphinx.builders.epub (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/epub.py
#   sphinx.builders.html (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/html.py
#   sphinx.builders.gettext (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/gettext.py
#   sphinx.builders.text (builtin) from /home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/text.py
Traceback (most recent call last):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 27, in map_node
    return cls._mapping[node_name.replace('-', '_')](node)
KeyError: 'math'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/cmdline.py", line 297, in main
    return app.statuscode
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/util/docutils.py", line 29, in docutils_namespace
    yield
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/sphinx/__init__.py", line 220, in write
    targetname)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/sphinx/__init__.py", line 228, in write_doc
    rinoh_tree = parser.from_doctree(source_path, doctree)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 124, in from_doctree
    flowables = mapped_tree.children_flowables()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/sphinx/nodes.py", line 217, in build_flowable
    return super().build_flowable(id='%' + self.get('docname'), **kwargs)
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 159, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 122, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 84, in flowables
    for flowable in super().flowables():
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 134, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 143, in build_flowables
    yield self.build_flowable()
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/nodes.py", line 194, in build_flowable
    return rt.Paragraph(super().process_content())
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/rst/__init__.py", line 62, in process_content
    children_text = (child.styled_text() for child in self.getchildren())
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 63, in getchildren
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 63, in <listcomp>
    return [self.map_node(child) for child in self.node_children(self.node)]
  File "/home/tom/.virtualenvs/tom3/lib/python3.5/site-packages/rinoh/frontend/__init__.py", line 32, in map_node
    cls.__module__))
NotImplementedError: None:None the 'math' node is not yet supported (rinoh.frontend.rst.nodes)

**Comment by brechtm** [comment]
There is no support for rendering maths at this point. It is not clear when this will be available. See #42.
